### PR TITLE
Function context

### PR DESCRIPTION
**Pull request by clarkmcc**

### CODE REVIEW

**Comment by clarkmcc** [comment]
Oops, wrong one again

**Comment by orf** [comment]
Hey @clarkmcc - I’ve invited you to be an owner on all of the crates, and I was going to transfer this repository to you but I cannot due to your existing fork.

I will archive this one, but I’m also happy to transfer it to you if you want - you just need to delete your fork I think.

**Comment by clarkmcc** [comment]
Thanks! No need to transfer, I can keep working off my fork unless that seems like a bad idea to you.

**Comment by orf** [comment]
No, it’s all good. I’ll archive this one - feel free to send me an email if publishing the crate doesn’t work or whatever! And good luck

**Pull request closed without merging**
